XML_NAMESPACES = {
    "chkl": "http://www.sap.com/abapxml/checklist",
    "atom": "http://www.w3.org/2005/Atom",
    "adtcore": "http://www.sap.com/adt/core",
    "exc": "http://www.sap.com/abapxml/types/communicationframework",
    "asx": "http://www.sap.com/abapxml",
    "aunit": "http://www.sap.com/adt/aunit",
    "chkrun": "http://www.sap.com/adt/checkrun",
    "abapsource": "http://www.sap.com/adt/abapsource",
    "opr": "http://www.sap.com/adt/ris/objectProperties",
    "tm": "http://www.sap.com/cts/adt/tm",
    "dataPreview": "http://www.sap.com/adt/dataPreview",
    "nameditem": "http://www.sap.com/adt/nameditem",
    "atcinfo": "http://www.sap.com/adt/atc/info",
    "atcobject": "http://www.sap.com/adt/atc/object",
    "atcfinding": "http://www.sap.com/adt/atc/finding",
    "usagereferences": "http://www.sap.com/adt/ris/usageReferences",
    "dump": "http://www.sap.com/adt/categories/dump",
}
